server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**

        # --- CẤU HÌNH CHO ORDER SERVICE ---
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/** # Nếu user gọi localhost:9000/api/order/... thì dẫn vào đây

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

  # --- KIỂM TRA KỸ ĐOẠN NÀY ---
  security:
    oauth2:
      resourceserver:
        jwt:
          # Đảm bảo dòng này còn tồn tại và đúng địa chỉ Keycloak của bạn
          issuer-uri: http://localhost:8180/realms/ecommerce-realm

# Cấu hình Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      productService:
        # Nếu 50% request bị lỗi -> Ngắt cầu dao (Open State)
        failure-rate-threshold: 50
        # Thời gian chờ đợi trước khi thử mở lại cầu dao -> 5 giây
        wait-duration-in-open-state: 5000
        # Số lượng request tối thiểu để bắt đầu tính toán tỷ lệ lỗi
        sliding-window-size: 5
  timelimiter:
    instances:
      productService:
        # Thời gian timeout: Nếu gọi sang Product quá 3 giây mà chưa xong -> Coi là lỗi
        timeout-duration: 3s

# Format log để hiện Trace ID và Span ID
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0 # 1.0 nghĩa là 100% request đều được gắn Trace ID
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans" # Địa chỉ gửi báo cáo
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus" # Quan trọng nhất là chữ 'prometheus'
    metrics:
      tags:
        application: ${spring.application.name} # Gán tên service vào dữ liệu để dễ lọc